config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    post '/finish_sign_in' => 'omniauth_callbacks#finish_sign_in'
  end
  
  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
        get :others, on: :collection
      end
      resources :questions do 
        resources :answers
      end 
    end
  end

  root 'questions#index'

  resources :attachments, only: :destroy

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
      patch :vote_cancel
    end
  end

  concern :subsribable do
    member do
      patch :subscribe
      patch :unsubscribe
    end
  end


  resources :questions, concerns: [:votable, :subsribable] do
    resources :comments, only: :create, defaults: {commentable: 'questions'}
    resources :answers, concerns: :votable do
      resources :comments, only: :create, defaults: {commentable: 'answers'}
      patch :best, on: :member
    end
  end

  resources :answers, concerns: :votable 

  get 'searches', to: 'searches#index'










end

app/models/question.rb
class Question < ActiveRecord::Base
  include Votable
  include Commentable
  include Subscribable

  has_many :answers, dependent: :destroy
  has_many :attachments, as: :attachable, dependent: :destroy
  belongs_to :user
  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true
  after_create :subscribe_owner

  scope :yesterdays, -> { where(created_at: Time.current.yesterday.all_day) }

  validates :title, :body, :user_id, presence: true
  validates :title, :body, length: { minimum: 10 }

  def channel_path
    "/questions/#{id}/comments"
  end 

  after_create :update_reputation

  private

  def update_reputation
    CalculateReputationJob.perform_later(self)
  end

  def subscribe_owner
    subscribe(self.user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  authorize_resource class: Question

  def index
    # https://github.com/rails-api/active_model_serializers/blob/master/docs/general/rendering.md#explicit-serializer
    # render json: @posts, serializer: CollectionSerializer, each_serializer: PostPreviewSerializer
    # render json: @user_post, root: "admin_post", adapter: :json
    respond_with Question.all, each_serializer: QuestionCollectionSerializer
  end

  def show
    respond_with Question.find(params[:id])
  end

  def create
    respond_with current_user.questions.create(question_params)
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: [:show, :index]
  # before_action :load_question, only: [:show, :edit, :update, :destroy, :vote_up, :vote_down, :vote_cancel]
  before_action :load_question, except: [:index, :new, :create]
  before_action :build_answer, only: :show
  after_action :publish_question, only: :create
  # skip_authorization_check 

  respond_to :js 
  # respond_to :json, only: [:subscribe, :unsubscribe]
  
  authorize_resource 

  def index
    respond_with(@questions = Question.all)
  end

  def show
    respond_with @question
  end

  def new
    respond_with(@question = Question.new)
  end

  def edit
  end

  def create
    respond_with(@question = Question.create(question_params.merge(user: current_user)))
  end

  def update
    @question.update(question_params)
    respond_with @question
  end

  def destroy
    respond_with @question.destroy
  end

  def subscribe
    @question.subscribe(current_user) 
    render 'subscriptions/subscribed' 
  end

  def unsubscribe
    @question.unsubscribe(current_user) 
    render 'subscriptions/subscribed' 
  end

  private

  def load_question
    @question = Question.find params[:id]
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:id, :file, :_destroy])
  end

  def build_answer
    @answer = @question.answers.build
  end

  def publish_question
    # PrivatePub.publish_to("/questions", question: @question.to_json) if @question.valid?
    PrivatePub.publish_to("/questions", question: @question.to_json) unless @question.errors.present?
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_comments.html.slim
.question-comments
  p Comments:
  .question-comments-list
    ul
      = render question.comments
  - if user_signed_in?
    .question-comments-errors
    .question-comments-form
      / # = render 'comments/form', comment: resource.comments.new, commentable: resource
      = render 'comments/form', form_path: [question, question.comments.new], commentable: question

app/views/questions/_form.html.slim
= form_for @question, remote: remote do |f| 
  p = f.label :title 
  = f.text_field :title , placeholder: 'Title you question'
  p = f.label :body 
  = f.text_area :body, placeholder: 'Body you question'
  = render 'attachments/attachment_form', f: f
  p = f.submit submit_text

app/views/questions/_question.html.slim
- cache_if (user_signed_in?), ['user', @question] do
  p: strong = @question.title
  p = @question.body
= render 'attachments/attachment_list', resource: @question
= render 'questions/vote', question: @question
= render 'questions/subscription', question: @question
/#- if user_signed_in?
- if can?(:crud, @question)  
  / # = link_to 'Edit', edit_question_path(@question)
  .question-errors
    = render 'shared/error', resource: @question    
  
  => link_to 'Edit', '', class: 'edit-question-link'
  => link_to 'Delete', 
              [@question], 
              class: 'delete-question-link',
              data: { question_id: @question.id, confirm: 'Sure?' }, 
              method: :delete      
  .edit-question-form
    = render partial: 'questions/form', locals: {submit_text: 'Edit Question', remote: true}

= render 'questions/comments', question: @question   

app/views/questions/_subscription.html.slim
div[class="question-subscription #{ 'subscribed' if question.subscribed?(current_user)}"]
  - if can?(:subscribe, question) || can?(:unsubscribe, question)
    => link_to 'Subscribe', 
                [:subscribe, question],
                method: :patch,
                data: { type: :json },
                class: "question-subscribe-link",
                remote: true
    => link_to 'Unsubscribe', 
                [:unsubscribe, question],
                method: :patch,
                data: { type: :json },
                class: "question-unsubscribe-link",
                remote: true

app/views/questions/_vote.html.slim
div[class="question-vote #{ 'has-vote' if question.voted(current_user)}"]
  p 
    |Votes:
    span[id="question-vote-count"] = question.votes.count
  p 
    |Rating:
    span[id="question-vote-rating"] = question.votes.rating

  - if can?(:vote, question)
    /#-unless question.user == current_user 
    => link_to 'Vote up', 
                [:vote_up, question],
                method: :patch,
                data: { type: :json },
                class: "question-vote-up-link",
                remote: true
    => link_to 'Vote cancel', 
                [:vote_cancel, question],
                method: :patch,
                data: { type: :json },
                class: "question-vote-cancel-link",
                remote: true
    => link_to 'Vote down', 
                [:vote_down, question],
                method: :patch,
                data: { type: :json },
                # id: "question-vote-down-link-#{question.id}",
                class: "question-vote-down-link", 
                # style: "display: #{}",                 
                remote: true

app/views/questions/edit.html.slim
h1 Edit question
= link_to 'Back to details', question_path(@question)
= render partial: 'form', locals: {submit_text: 'Edit Question', remote: false}  

app/views/questions/index.html.slim
h1 Questions list
- if current_user
  => link_to 'Log out', destroy_user_session_path, method: :delete
- else
  => link_to 'Log in', new_user_session_path
  => link_to 'Register', new_user_registration_path
hr
= render 'searches/form' 

- if can?(:create, Question)
  = link_to 'Ask your question', new_question_path

- cache collection_cache_key_for :question do
  .questions
  - unless @questions.empty?
    - @questions.each do |question|
      p
        = question.title
        =< link_to 'Details', question_path(question)
  - else
    p No questions found.

= subscribe_to "/questions"

app/views/questions/new.html.slim
h1 New question
= link_to 'Back to list', questions_path  
.question-errors
  = render 'shared/error', resource: @question   
= render partial: 'form', locals: {submit_text: 'Create Question', remote: false} 

app/views/questions/show.html.slim
- cache_if (not user_signed_in?), ['guest', @question] do
  h1 Question
  = link_to 'Back to list', questions_path 
  .question data={ question_id: "#{@question.id}" }
    = render 'question'
  hr

  h2 Answers
  /- if @question.answers.present?
  - unless @question.answers.empty?
    .answers
      /- @question.answers.each do |answer|
      / = render 'answers'
      = render @question.answers
  - else
    p No answers found.

  - if user_signed_in?
    h3 Add answer
    #add-answer-errors
    = render partial: 'answers/form', locals: {answer: @answer ,submit_text: 'Create Answer'}

= subscribe_to "/questions/#{@question.id}/comments"
= subscribe_to "/questions/#{@question.id}/answers"

app/views/questions/update.js.erb
<% if @question.errors.present? %>
  $('.question-errors').html("<%= j render 'shared/error', resource: @question %>");
<% else %>  
  <% if remotipart_submitted? %>
      $('.question').html('<%= j "#{render 'question'}" %>');
  <% else %>
      $('.question').html("<%= j render 'question' %>");
  <% end %>
<% end %>