config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    post '/finish_sign_in' => 'omniauth_callbacks#finish_sign_in'
  end
  
  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
        get :others, on: :collection
      end
      resources :questions do 
        resources :answers
      end 
    end
  end

  root 'questions#index'

  resources :attachments, only: :destroy

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
      patch :vote_cancel
    end
  end

  concern :subsribable do
    member do
      patch :subscribe
      patch :unsubscribe
    end
  end


  resources :questions, concerns: [:votable, :subsribable] do
    resources :comments, only: :create, defaults: {commentable: 'questions'}
    resources :answers, concerns: :votable do
      resources :comments, only: :create, defaults: {commentable: 'answers'}
      patch :best, on: :member
    end
  end

  resources :answers, concerns: :votable 

  get 'searches', to: 'searches#index'










end

app/models/search.rb
class Search
  SEARCH_OPTIONS = %w(Questions Answers Comments Users)

  def self.main(query, options = nil)
    query = Riddle::Query.escape(query)
    if options.present?
      options.singularize.constantize.search(query)
    else
      ThinkingSphinx.search query
    end
  end

  def self.params_valid?(query, options = nil)
    return false unless query.present?
    return true unless options.present?
    return true if SEARCH_OPTIONS.include?(options)
    false
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  skip_authorization_check

  def index
    if Search.params_valid?(params[:query], params[:options])
      @search = Search.main(params[:query], params[:options]) 
      respond_with @search
    else
      flash[:notice] = "Invalid query"
      redirect_to :back
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/searches/_answer.html.slim
h2 Answer:
p = link_to truncate(answer.body, length: 200), question_path(answer.question)

app/views/searches/_comment.html.slim
h2 Comment:
- if comment.commentable.class == Question
  p = link_to truncate(comment.body, length: 200), question_path(comment.commentable)
- else
  p = link_to truncate(comment.body, length: 200), question_path(comment.commentable.question)
  / #p = truncate(comment.body, length: 200)
  / #p = truncate(comment.body, length: 200)

app/views/searches/_form.html.slim
= form_tag searches_path, method: :get  
  =< search_field_tag :query, params[:query], placeholder: 'Query'
  =< select_tag(:options, 
               options_for_select(Search::SEARCH_OPTIONS, 
                                  params[:options]), prompt: 'All')
  =< submit_tag 'Search', name: nil

app/views/searches/_question.html.slim
h2 Question:
p = link_to question.title, question_path(question)

app/views/searches/_user.html.slim
h2 User:
p = user.email

app/views/searches/index.html.slim
h1 Search results:
= link_to 'Back to list', questions_path 
- if @search.present?
  - @search.each do |object|
    = render partial: "#{object.class.name.downcase}", object: object
- else
    p No results.